#this is a test
BungeeCord: false
Command:
  Ban: ban
  Purge: purge
  Info: info
  TempBan: tempban
  Warning: warning
MaxWarnings: 5
Worlds:
  Purgatory: hell
  Default: world
UpdateChecker: true
Force-Spawn-Default-World: false
Force-Spawn-Purgatory-World: true
Force-Spawn-Unban: false
Force-Kick: true
Title-Warning: false
ScoreBoard-CountDown-Tasks: true
